### ISSUE TITLE
Doesn't compatible with ARM64 arch

### ISSUE THREAD

**Issue by fireflyoo** [SirMonkeyBoy/Crossplay#4]
Could you build a ARM64 binary  version?

**Comment by SirMonkeyBoy** [comment]
ok I'll try

**Comment by SirMonkeyBoy** [comment]
I've added a ARM64 Crossplay in releases I can't test it as i don't have a arm computer so if it works can you tell me

**Comment by fireflyoo** [comment]
Saddly ,it doesn't work

`[Server API] Error Crossplay_arm64.dll was built for X64 but expected it to be compatible with Arm64.
[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Failed to load assembly "Crossplay_arm64.dll".
 ---> System.IO.FileLoadException: Could not load file or assembly 'Crossplay, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 343
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 414
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 116
   at TerrariaApi.Server.HookManager.InitialiseAPI() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HookManager.cs:line 29`

**Comment by SirMonkeyBoy** [comment]
ok give me a min and I'll try something then rebuild it

**Comment by SirMonkeyBoy** [comment]
ok I've changed updated the arm64 file

**Comment by fireflyoo** [comment]
> ok I've updated the arm64 file

thanks for your work,Now it works well.
